# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4IceG
          config_timezone: Europe/Warsaw
          use_prebuilt_image: master
          base: "header, repositories"
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
      - name: GitHub Discussions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4IceG
          base: ""
          config_timezone: Europe/Warsaw
          use_prebuilt_image: master
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
