# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sponsors goal
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: 4IceG
          config_timezone: Europe/Warsaw
          use_prebuilt_image: master
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
