# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  watch:
    types: started
  # Lines below let you run workflow manually and on each commit    
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Example
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        user: 4IceG
        base: header, repositories
        config_timezone: Europe/Warsaw
        plugin_lines: yes
