name: Sponsors goal
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: started    
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
- name: Sponsors goal
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.sponsors.svg
    token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
    base: ""
    plugin_sponsors: yes
    plugin_sponsors_sections: goal, list
    plugin_sponsors_past: yes

- name: Sponsors introduction
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.sponsors.full.svg
    token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
    base: ""
    plugin_sponsors: yes
