name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: started    
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
    - name: Sponsors goal
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          user: 4IceG
          config_timezone: Europe/Warsaw
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
