name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
    types: started    
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: 4IceG
          config_timezone: Europe/Warsaw
          config_order: base.header, isocalendar, base.repositories, followup, pagespeed, people
          config_padding: 10%
          use_prebuilt_image: master
          base: "header, repositories"
          plugin_isocalendar: yes
          #          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_traffic: yes

          plugin_followup: yes

          plugin_pagespeed: no
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: 
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 28
          plugin_people_size: 28
